# Generated by Django 6.0.1 on 2026-01-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDb',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('Emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
